### ISSUE TITLE
Exception in thread "main" java.util.InputMismatchException

### ISSUE THREAD

**Issue by alvessh** [guilhermezimmermann/teste-presenca#5]
Choose a option: 

1 - List
2 - Insert
3 - Update
4 - Delete
5 - Exit
Enter a number: Um
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at Application.main(Application.java:24)

**Comment by Guilherme-Zimmermann** [comment]
Isso resolve o seu problema?

**Comment by alvessh** [comment]
Programa de Controle de tarefas
Escolha uma opção: 

Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair
Você deseja: Um
Valor inválido inserido!

**Comment by alvessh** [comment]
> Isso resolve o seu problema?

Programa de Controle de tarefas
Escolha uma opção:

Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair
Você deseja: Um
Valor inválido inserido!


A questão é que me retorna "Valor inválido inserido!", porém não consigo adicionar valores correto, apartir disso.

Ou seja, se EU inserir valor inválido, não volta novamente para listagem de opções..

**Comment by alvessh** [comment]
Título da tarefa: A
Descrição: A
Digite (1) se a tarefa estiver PENDENTE
Digite (2) se a tarefa estiver COMPLETO
Status: 1

Digite (1) Para listar todas suas tarefas
Digite (2) Para inserir uma nova tarefa
Digite (3) Para alterar uma tarefa
Digite (4) Para deletar uma tarefa
Digite (5) Para sair da aplicação
Insira uma opção: 3

Id da tarefa que deseja alterar: B
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at Application.main(Application.java:54)
